[package]
name = "cggtts"
version = "3.2.2"
license = "MIT OR Apache-2.0"
authors = ["Guillaume W. Bres <guillaume.bressaix@gmail.com>"]
description = "Package to analyze and create CGGTTS data"
homepage = "https://github.com/gwbres/cggtts"
keywords = ["positionning","bipm","gnss","timing","satellites"]
categories = ["science","parsing"]
edition = "2018"
readme = "../README.md"

[features]
default = [] # no features by default

[dependencies]
thiserror = "1"
chrono = "0.4"
scan_fmt = "0.1"
julianday = "1.1.0"
# rinex = { version = "0.4.0", features = ["serde"] } 
rust-3d = "0.34.0"
format_num = "0.1.0"
strum = "0.23.0"
strum_macros = "0.23.0"
gnss-rs = { version = "2.1", features = ["serde"] }
hifitime = { version = "3.8.4", features = ["serde", "std"] }
serde = { version = "1.0", optional = true, features = ["derive"] }
